# Generated by Django 5.1.15 on 2026-04-14 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genealogy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genealogy_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=64)),
                ('compiled_at', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.RESTRICT, related_name='created_genealogies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'genealogies',
                'ordering': ['title', 'genealogy_id'],
            },
        ),
        migrations.CreateModel(
            name='GenealogyInvitation',
            fields=[
                ('invitation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('accepted', '已接受'), ('declined', '已拒绝'), ('revoked', '已撤销'), ('expired', '已过期')], default='pending', max_length=16)),
                ('message', models.TextField(blank=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('genealogy', models.ForeignKey(db_column='genealogy_id', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='genealogy.genealogy')),
                ('invitee_user', models.ForeignKey(db_column='invitee_user_id', on_delete=django.db.models.deletion.RESTRICT, related_name='received_genealogy_invitations', to=settings.AUTH_USER_MODEL)),
                ('inviter_user', models.ForeignKey(db_column='inviter_user_id', on_delete=django.db.models.deletion.RESTRICT, related_name='sent_genealogy_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'genealogy_invitations',
                'ordering': ['-invited_at', '-invitation_id'],
            },
        ),
        migrations.CreateModel(
            name='GenealogyCollaborator',
            fields=[
                ('collaborator_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('editor', '编辑者'), ('viewer', '只读')], default='editor', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, db_column='added_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_genealogy_collaborators', to=settings.AUTH_USER_MODEL)),
                ('genealogy', models.ForeignKey(db_column='genealogy_id', on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='genealogy.genealogy')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.RESTRICT, related_name='genealogy_collaborations', to=settings.AUTH_USER_MODEL)),
                ('source_invitation', models.OneToOneField(db_column='source_invitation_id', on_delete=django.db.models.deletion.RESTRICT, related_name='activated_collaborator', to='genealogy.genealogyinvitation')),
            ],
            options={
                'db_table': 'genealogy_collaborators',
                'ordering': ['genealogy_id', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('surname', models.CharField(blank=True, max_length=64)),
                ('given_name', models.CharField(blank=True, max_length=128)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='unknown', max_length=16)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
                ('is_living', models.BooleanField(default=True)),
                ('generation_label', models.CharField(blank=True, max_length=64)),
                ('seniority_text', models.CharField(blank=True, max_length=64)),
                ('branch_name', models.CharField(blank=True, max_length=128)),
                ('biography', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL)),
                ('genealogy', models.ForeignKey(db_column='genealogy_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='genealogy.genealogy')),
            ],
            options={
                'db_table': 'members',
                'ordering': ['genealogy_id', 'full_name', 'member_id'],
            },
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marriage_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('married', '婚姻存续'), ('divorced', '离异'), ('widowed', '丧偶'), ('unknown', '未知')], default='married', max_length=16)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_marriages', to=settings.AUTH_USER_MODEL)),
                ('genealogy', models.ForeignKey(db_column='genealogy_id', on_delete=django.db.models.deletion.CASCADE, related_name='marriages', to='genealogy.genealogy')),
                ('member_a', models.ForeignKey(db_column='member_a_id', on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_a', to='genealogy.member')),
                ('member_b', models.ForeignKey(db_column='member_b_id', on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_b', to='genealogy.member')),
            ],
            options={
                'db_table': 'marriages',
                'ordering': ['genealogy_id', 'member_a_id', 'member_b_id'],
            },
        ),
        migrations.CreateModel(
            name='MemberEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('migration', '迁徙'), ('residence', '居住'), ('occupation', '任职'), ('achievement', '成就'), ('burial', '安葬'), ('marriage_note', '婚配记载'), ('other', '其他')], max_length=32)),
                ('event_year', models.IntegerField(blank=True, null=True)),
                ('place_text', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('genealogy', models.ForeignKey(db_column='genealogy_id', on_delete=django.db.models.deletion.CASCADE, related_name='member_events', to='genealogy.genealogy')),
                ('member', models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='genealogy.member')),
                ('recorded_by', models.ForeignKey(blank=True, db_column='recorded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_member_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member_events',
                'ordering': ['genealogy_id', 'member_id', 'event_year', 'event_id'],
            },
        ),
        migrations.CreateModel(
            name='ParentChildRelation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parent_role', models.CharField(choices=[('father', '父亲'), ('mother', '母亲')], max_length=16)),
                ('child_member', models.ForeignKey(db_column='child_member_id', on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='genealogy.member')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parent_child_relations', to=settings.AUTH_USER_MODEL)),
                ('genealogy', models.ForeignKey(db_column='genealogy_id', on_delete=django.db.models.deletion.CASCADE, related_name='parent_child_relations', to='genealogy.genealogy')),
                ('parent_member', models.ForeignKey(db_column='parent_member_id', on_delete=django.db.models.deletion.CASCADE, related_name='children_relations', to='genealogy.member')),
            ],
            options={
                'db_table': 'parent_child_relations',
                'ordering': ['genealogy_id', 'child_member_id', 'parent_role'],
            },
        ),
        migrations.AddConstraint(
            model_name='genealogy',
            constraint=models.CheckConstraint(condition=models.Q(('compiled_at__isnull', True), models.Q(('compiled_at__gte', 1), ('compiled_at__lte', 3000)), _connector='OR'), name='genealogies_compiled_at_range'),
        ),
        migrations.AddConstraint(
            model_name='genealogyinvitation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'accepted', 'declined', 'revoked', 'expired'])), name='genealogy_invitations_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='genealogyinvitation',
            constraint=models.CheckConstraint(condition=models.Q(('inviter_user', models.F('invitee_user')), _negated=True), name='genealogy_invitations_not_self'),
        ),
        migrations.AddConstraint(
            model_name='genealogyinvitation',
            constraint=models.CheckConstraint(condition=models.Q(('responded_at__isnull', True), ('responded_at__gte', models.F('invited_at')), _connector='OR'), name='genealogy_invitations_response_after_invite'),
        ),
        migrations.AddConstraint(
            model_name='genealogyinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('genealogy', 'invitee_user'), name='genealogy_invitations_pending_once'),
        ),
        migrations.AddConstraint(
            model_name='genealogycollaborator',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['editor', 'viewer'])), name='genealogy_collaborators_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='genealogycollaborator',
            constraint=models.UniqueConstraint(fields=('genealogy', 'user'), name='genealogy_collaborators_unique_user_per_genealogy'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['genealogy', 'full_name'], name='members_genealogy_name_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['genealogy', 'gender'], name='members_genealogy_gender_idx'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.CheckConstraint(condition=models.Q(('gender__in', ['male', 'female', 'unknown'])), name='members_gender_valid'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.CheckConstraint(condition=models.Q(('birth_year__isnull', True), models.Q(('birth_year__gte', 1), ('birth_year__lte', 3000)), _connector='OR'), name='members_birth_year_range'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.CheckConstraint(condition=models.Q(('death_year__isnull', True), models.Q(('death_year__gte', 1), ('death_year__lte', 3000)), _connector='OR'), name='members_death_year_range'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.CheckConstraint(condition=models.Q(('death_year__isnull', True), ('birth_year__isnull', True), ('birth_year__lte', models.F('death_year')), _connector='OR'), name='members_birth_before_death'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.CheckConstraint(condition=models.Q(('is_living', False), ('death_year__isnull', True), _connector='OR'), name='members_living_has_no_death_year'),
        ),
        migrations.AddIndex(
            model_name='marriage',
            index=models.Index(fields=['genealogy', 'member_a'], name='marriages_member_a_idx'),
        ),
        migrations.AddIndex(
            model_name='marriage',
            index=models.Index(fields=['genealogy', 'member_b'], name='marriages_member_b_idx'),
        ),
        migrations.AddConstraint(
            model_name='marriage',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['married', 'divorced', 'widowed', 'unknown'])), name='marriages_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='marriage',
            constraint=models.CheckConstraint(condition=models.Q(('member_a', models.F('member_b')), _negated=True), name='marriages_not_self'),
        ),
        migrations.AddConstraint(
            model_name='marriage',
            constraint=models.CheckConstraint(condition=models.Q(('member_a__lt', models.F('member_b'))), name='marriages_canonical_member_order'),
        ),
        migrations.AddConstraint(
            model_name='marriage',
            constraint=models.CheckConstraint(condition=models.Q(('end_year__isnull', True), ('start_year__isnull', True), ('start_year__lte', models.F('end_year')), _connector='OR'), name='marriages_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='marriage',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'married')), fields=('genealogy', 'member_a', 'member_b'), name='marriages_single_active_pair'),
        ),
        migrations.AddIndex(
            model_name='memberevent',
            index=models.Index(fields=['genealogy', 'member', 'event_type', 'event_year'], name='member_events_timeline_idx'),
        ),
        migrations.AddConstraint(
            model_name='memberevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['migration', 'residence', 'occupation', 'achievement', 'burial', 'marriage_note', 'other'])), name='member_events_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='memberevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_year__isnull', True), models.Q(('event_year__gte', 1), ('event_year__lte', 3000)), _connector='OR'), name='member_events_year_range'),
        ),
        migrations.AddIndex(
            model_name='parentchildrelation',
            index=models.Index(fields=['genealogy', 'parent_member'], name='pcr_parent_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='parentchildrelation',
            index=models.Index(fields=['genealogy', 'child_member'], name='pcr_child_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='parentchildrelation',
            constraint=models.CheckConstraint(condition=models.Q(('parent_role__in', ['father', 'mother'])), name='parent_child_relations_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='parentchildrelation',
            constraint=models.CheckConstraint(condition=models.Q(('parent_member', models.F('child_member')), _negated=True), name='parent_child_relations_not_self'),
        ),
        migrations.AddConstraint(
            model_name='parentchildrelation',
            constraint=models.UniqueConstraint(fields=('genealogy', 'parent_member', 'child_member', 'parent_role'), name='parent_child_relations_unique_edge'),
        ),
        migrations.AddConstraint(
            model_name='parentchildrelation',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_role', 'father')), fields=('genealogy', 'child_member'), name='parent_child_relations_single_father'),
        ),
        migrations.AddConstraint(
            model_name='parentchildrelation',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_role', 'mother')), fields=('genealogy', 'child_member'), name='parent_child_relations_single_mother'),
        ),
    ]
