# Generated by Django 5.1.15 on 2026-04-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['username'],
            },
        ),
    ]
